version: 2
build:
  os: ubuntu-24.04
  tools:
    python: '3.13'
  jobs:
    pre_build:
      - cp -a locales project/docs/
submodules:
  include: all
python:
  install:
    - requirements: project/requirements/docs.txt
    - method: pip
      path: project
sphinx:
  builder: dirhtml
  fail_on_warning: true
